- id: Sunset
  alias: Sunset Lights
  trigger:
    - platform: sun
      event: sunset
      offset: "-1:00:00"
  action:
    - service: switch.turn_on
      entity_id: switch.TP_Plug

- id: Sunrise
  alias: Sunrise Lights
  trigger:
    - platform: sun
      event: sunrise
      offset: "1:00:00"
  action:
    - service: switch.turn_on
      entity_id: switch.TP_Plug